import Link from "next/link"
import { notFound } from "next/navigation"
import { requireAdmin } from "@/lib/auth"
import { linkQuizAttempt } from "@/app/settings/actions"
import { Shell } from "@/components/product/shell"
import { Button } from "@/components/ui/button"

export default async function QuizAttemptPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { supabase, membership } = await requireAdmin()
  const { data: attempt } = await supabase.from("public_quiz_attempts").select("id,organization_id,quiz_id,participant_id,full_name,age_years,answers,result,created_at").eq("id", id).eq("organization_id", membership.organization_id).single()
  if (!attempt) notFound()
  const { data: participants } = await supabase.from("participants").select("id,display_name,code").eq("organization_id", membership.organization_id).is("archived_at", null).order("display_name")
  const answers = attempt.answers as { question_id: string; value: string }[]
  const result = attempt.result as { correct: number; total: number; graded: { question_id: string; status: string }[]; questions: { id: string; section: string; prompt: string; answer: string }[] }
  return <Shell title={attempt.full_name} eyebrow="Hasil posttest mandiri" admin action={<Button render={<Link href="/settings/quiz" />} variant="outline">Kembali ke kiriman</Button>}><div className="surface mb-6 p-5"><p className="text-sm text-[#4d6156]">Umur {attempt.age_years} tahun · Dikirim {new Date(attempt.created_at).toLocaleString("id-ID")}</p><p className="mt-3 font-heading text-3xl">{result.correct} dari {result.total} jawaban tepat</p><p className="mt-2 text-sm text-[#4d6156]">Skor ini tidak dikonversi menjadi level Tangga Angka.</p></div><form action={linkQuizAttempt} className="surface mb-6 max-w-xl space-y-3 p-5"><h2 className="font-heading text-xl">Tautkan ke peserta</h2><p className="text-sm text-[#4d6156]">Periksa identitas sebelum menautkan. Nama yang sama belum tentu peserta yang sama.</p><input type="hidden" name="attempt_id" value={attempt.id} /><label className="block text-sm font-semibold">Peserta<select name="participant_id" className="field mt-2" defaultValue={attempt.participant_id ?? ""}><option value="">Belum ditautkan</option>{participants?.map((participant) => <option key={participant.id} value={participant.id}>{participant.display_name}{participant.code ? ` · ${participant.code}` : ""}</option>)}</select></label><Button type="submit">Simpan tautan</Button></form><section className="space-y-3"><h2 className="font-heading text-2xl">Jawaban per soal</h2>{result.questions.map((question) => { const answer = answers.find((item) => item.question_id === question.id); const status = result.graded.find((item) => item.question_id === question.id)?.status; return <div key={question.id} className="surface p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a9432b]">{question.section}</p><h3 className="mt-1 font-heading text-xl">{question.prompt}</h3><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><div><dt className="text-[#4d6156]">Jawaban peserta</dt><dd className="font-semibold">{answer?.value ?? "Dilewati"}</dd></div><div><dt className="text-[#4d6156]">Kunci</dt><dd className="font-semibold">{question.answer}</dd></div><div><dt className="text-[#4d6156]">Status</dt><dd className="font-semibold">{status === "correct" ? "Tepat" : status === "incorrect" ? "Belum tepat" : "Dilewati"}</dd></div></dl></div> })}</section></Shell>
}
