"use client"
import Link from "next/link"
import { useState } from "react"
import { finalizeAssessment, saveObservation } from "@/app/assessments/actions"
import { Button } from "@/components/ui/button"

export function ReviewForm({ id, revision, observation }: { id: string; revision: number; observation: { counting_method: string | null; explanation: string | null; difficulty_response: string | null; tools: string[]; motivator: string | null; note: string | null } | null }) {
  const [counting, setCounting] = useState(observation?.counting_method ?? "")
  const [explanation, setExplanation] = useState(observation?.explanation ?? "")
  const [difficulty, setDifficulty] = useState(observation?.difficulty_response ?? "")
  const [tools, setTools] = useState(observation?.tools ?? [])
  const [motivator, setMotivator] = useState(observation?.motivator ?? "")
  const [note, setNote] = useState(observation?.note ?? "")
  const [state, setState] = useState("")
  const [busy, setBusy] = useState(false)
  const [reason, setReason] = useState("")
  async function save() {
    setBusy(true); setState("Menyimpan catatan...")
    try { await saveObservation(id, { counting_method: counting || null, explanation: explanation || null, difficulty_response: difficulty || null, tools, motivator, note }); setState("Catatan tersimpan") }
    catch (error) { setState(error instanceof Error ? error.message : "Catatan belum tersimpan") }
    finally { setBusy(false) }
  }
  return <aside className="space-y-5"><div className="surface p-5"><h2 className="font-heading text-xl">Catatan pengamatan</h2><p className="mt-2 text-xs leading-5 text-[#4d6156]">Tulis yang terlihat, bukan label. Contoh: “menghitung satu-satu dengan jari”, bukan “lambat”.</p><div className="mt-4 space-y-3"><Select label="Cara menghitung" value={counting} set={setCounting} options={["hitung dari 1","lanjut dari angka besar","langsung tahu","bersusun","menebak","lainnya"]} /><Select label="Menjelaskan cara" value={explanation} set={setExplanation} options={["bisa","sebagian","belum","tidak ditanyakan"]} /><Select label="Saat sulit" value={difficulty} set={setDifficulty} options={["mencoba lagi","meminta bantuan","diam","menghindar","marah/sedih","lainnya"]} /><fieldset><legend className="mb-2 text-sm font-semibold">Alat bantu</legend><div className="flex flex-wrap gap-2">{["jari","benda konkret","gambar/titik","coretan","prompt verbal"].map((item) => <label key={item} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#b7c7bf] px-3 text-sm"><input type="checkbox" checked={tools.includes(item)} onChange={(event) => setTools((previous) => event.target.checked ? [...previous,item] : previous.filter((value) => value !== item))} />{item}</label>)}</div></fieldset><label className="block text-sm font-semibold">Minat yang terlihat<input className="field mt-2" maxLength={300} value={motivator} onChange={(event) => setMotivator(event.target.value)} /></label><label className="block text-sm font-semibold">Catatan singkat<textarea className="field mt-2 min-h-24" maxLength={1000} value={note} onChange={(event) => setNote(event.target.value)} /></label><Button variant="outline" className="w-full" disabled={busy} onClick={save}>Simpan catatan</Button><p role="status" className="text-sm">{state}</p></div></div>
  <form action={finalizeAssessment.bind(null,id)} className="surface space-y-4 p-5"><h2 className="font-heading text-xl">Akhiri sesi</h2><p className="text-sm text-[#4d6156]">Tawarkan satu soal mudah sebagai penutup positif sebelum menyelesaikan. Penutup tidak mengubah hasil.</p><input name="revision" type="hidden" value={revision} /><label className="block text-sm font-semibold">Alasan berhenti<select name="stop_reason" required className="field mt-2" value={reason} onChange={(event) => setReason(event.target.value)}><option value="" disabled>Pilih alasan</option><option value="level_not_met">Kriteria level belum terpenuhi</option><option value="child_declined">Anak memilih berhenti</option><option value="all_levels_passed">Semua level dicoba</option><option value="time_limit">Waktu pertemuan selesai</option><option value="assessor_decision">Keputusan relawan</option></select></label>{reason === "assessor_decision" && <label className="block text-sm font-semibold">Alasan keputusan relawan<textarea name="override_reason" required minLength={5} maxLength={1000} className="field mt-2 min-h-20" /></label>}<label className="block text-sm font-semibold">Fokus pertemuan berikutnya<textarea name="summary_note" maxLength={2000} className="field mt-2 min-h-20" /></label><Button type="submit" className="w-full">Finalisasi sesi</Button><Button render={<Link href={`/assessments/${id}/run`} />} variant="outline" className="w-full">Koreksi jawaban</Button></form></aside>
}
function Select({ label, value, set, options }: { label: string; value: string; set: (value: string) => void; options: string[] }) { return <label className="block text-sm font-semibold">{label}<select className="field mt-2" value={value} onChange={(event) => set(event.target.value)}><option value="">Belum dicatat</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
